# Create a Gui calculator that can do basic math operations
import tkinter as tk

# Create a window
calculator = tk.Tk()
calculator.title("Calculator")
calculator.geometry("300x300")
calculator.configure(background="white")
# Place text box at the top center of the window
text_box = tk.Entry(calculator, width=45, borderwidth=5)
text_box.grid(column=0, row=0, columnspan=4, padx=10, pady=10)
# Place buttons at the bottom of the window
button_1 = tk.Button(calculator, text="1", padx=40, pady=20)
button_1.grid(column=0, row=3)
button_2 = tk.Button(calculator, text="2", padx=40, pady=20)
button_2.grid(column=1, row=3)
button_3 = tk.Button(calculator, text="3", padx=40, pady=20)
button_3.grid(column=2, row=3)
button_4 = tk.Button(calculator, text="4", padx=40, pady=20)
button_4.grid(column=0, row=2)
button_5 = tk.Button(calculator, text="5", padx=40, pady=20)
button_5.grid(column=1, row=2)
button_6 = tk.Button(calculator, text="6", padx=40, pady=20)
button_6.grid(column=2, row=2)
button_7 = tk.Button(calculator, text="7", padx=40, pady=20)
button_7.grid(column=0, row=1)
button_8 = tk.Button(calculator, text="8", padx=40, pady=20)
button_8.grid(column=1, row=1)
button_9 = tk.Button(calculator, text="9", padx=40, pady=20)
button_9.grid(column=2, row=1)
button_0 = tk.Button(calculator, text="0", padx=40, pady=20)
button_0.grid(column=1, row=4)
button_add = tk.Button(calculator, text="+", padx=40, pady=20)
button_add.grid(column=3, row=1)
button_subtract = tk.Button(calculator, text="-", padx=40, pady=20)
button_subtract.grid(column=3, row=2)
button_multiply = tk.Button(calculator, text="*", padx=40, pady=20)
button_multiply.grid(column=3, row=3)
button_divide = tk.Button(calculator, text="/", padx=40, pady=20)
button_divide.grid(column=3, row=4)
button_equal = tk.Button(calculator, text="=", padx=40, pady=20)
button_equal.grid(column=3, row=5)
button_clear = tk.Button(calculator, text="Clear", padx=40, pady=20)
button_clear.grid(column=0, row=5)
# Run the window
calculator.mainloop()